on: [push]

name: Build Docker images

jobs:
  build_code_maat:
    name: Build node lts
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      
    - name: Build Docker Images
      uses: philips-software/docker-ci-scripts@v2.0.1
      with:
        dockerfile: 1/alpine
        image-name: code-maat
        tags: latest 1 1.0 1.0.2 1.0.2-alpine
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
